# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20151127_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='max_file_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='max_space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
