# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20151209_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='free_space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
